name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção e Envio da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            moura1001/devops:devops4dev-reviewvideo-v${{ github.run_number }}
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4
      
      - name: Configuração do Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      
      - name: Execução do kubectl apply
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
          images: |
            moura1001/devops:devops4dev-reviewvideo-v${{ github.run_number }}